### ISSUE TITLE
Editor: After using tabs to traverse in the simulation tab, cannot scroll back up

### ISSUE THREAD

**Issue by Niveathika92** [wso2/carbon-analytics#1000]
**Description:**
After using tabs to traverse in the simulation, cannot scroll back up, have to use Shift+Tab to come to the top of the simulation
![issue](https://user-images.githubusercontent.com/27669465/34149242-71e17378-e4ca-11e7-9f4c-d20e86edb6a1.jpeg)

**Suggested Labels:**
Bug

**Comment by mohanvive** [comment]
Closed the issue since the fix is merged.
