### ISSUE TITLE
Feed simulation can be edit and delete when its running

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#1061]
**Description:**
Feed simulation can be edit and delete when it's running.  Edit Delete links should be disabled when a simulation is running.

**Suggested Labels:**
Editor, Bug, Severity/Minor, Priority/Low

**Affected Product Version:**
RC1

**Steps to reproduce:**
Create an App.
Create a feed simulaion.
Run the feed simulation.
Edit or delete the feed simulation

**Comment by ramindu90** [comment]
fixed with PR: https://github.com/wso2/carbon-analytics/pull/1093
