### ISSUE TITLE
Hostname verification configuration does not affect in connections through External IdPClient

### ISSUE THREAD

**Issue by Niveathika92** [wso2/carbon-analytics#1073]
**Description:**
Host name verification configuration does not affect in connections through External IdPClient

**Suggested Labels:**
Bug

**Affected Product Version:**
SP-4.0.0-RC2

**Steps to reproduce:**
1. Start IdP
2. Start SP in External IdP Client mode
3. Hostname is verified in the connection.(Should be false by default)

**Comment by mohanvive** [comment]
@Niveathika92 Isn't this fixed now ?

**Comment by Niveathika92** [comment]
No, as the PR for the fix https://github.com/wso2/carbon-analytics-common/pull/505 is not merged yet.
