### ISSUE TITLE
Delete should only be applicable for saved siddhi apps. For other states it should be disabled

### ISSUE THREAD

**Issue by dnwick** [wso2/carbon-analytics#1082]
**Description:**
Delete should only be applicable for saved siddhi apps. For other states it should be disabled

**Comment by ramindu90** [comment]
@RAVEENSR add the PR here and close this if it fixes the issue

**Comment by RAVEENSR** [comment]
This was fixed in https://github.com/wso2/carbon-analytics/pull/1088 and improved in https://github.com/wso2/carbon-analytics/pull/1089
