### ISSUE TITLE
Distributed Deployment does not support multiple zookeeper servers

### ISSUE THREAD

**Issue by Anoukh** [wso2/carbon-analytics#1094]
**Description:**
Currently distributed deployment does not support multiple zookeeper servers. Only possible to add one zookeeper URL. Should be able to define multiple URLs of a zookeeper cluster in case of failover

**Suggested Labels:**
Feature enhancement
Component/Manager

**Suggested Assignees:**
Anoukh

**Affected Product Version:**
SP 4.x.x

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by mohanvive** [comment]
Closing the issue since it is fixed now.
