### ISSUE TITLE
Aggregation definition related error message is not shown

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/carbon-analytics#1120]
**Description:**
When trying to add a table as a input stream in aggregation definition it doesn't show an error message. 

**Affected Product Version:**
WSO2 Stream Processor 4.0.0 Release

**Steps to reproduce:**
Type the following in the siddhi app.

@App:name("cvbs")
@app:description("Description of the plan")

define table TradeStream (symbol string, price double, volume long, timestamp long);

define aggregation TradeAggregation
  from TradeStream
  select symbol, avg(price) as avgPrice, sum(price) as total
    group by symbol
    aggregate by timestamp every sec ... year;

![aggreagationerror](https://user-images.githubusercontent.com/19996612/34812457-a55dac36-f6cb-11e7-8a3e-3b414a006bf8.png)

**Comment by Niveathika92** [comment]
Closing as it is fixed in SP4.3.0 pack.
