### ISSUE TITLE
Problem with UPDATE queries in HA mode

### ISSUE THREAD

**Issue by sreenivaskolisetty** [wso2/carbon-analytics#1176]
**Description:**
HACoordinationRecordTableHandler is not passing update set parameter map (updateSetParameterMaps) to RecordTableHandlerCallback. As result of this, update set values not available in RecordTableHandlerCallback to populate values to UPDATE SET clause.

**Affected Product Version:**
WSO2 SP 4.0.0.0

**OS, DB, other environment details and versions:**    
HA mode
**Steps to reproduce:**
Update event table in siddhi app

**Comment by dilini-muthumala** [comment]
Thank you for reporting this!
This has being fixed in PR #1177 and merged in commit 04cda1c47829aca4473a4c937b4bcbe0b2e1896e.
