### ISSUE TITLE
[Editor] When side bar is visible , when showing errors, does not seem to align according to borders

### ISSUE THREAD

**Issue by dnwick** [wso2/carbon-analytics#1181]
<img width="1436" alt="screen shot 2018-03-13 at 1 08 20 pm" src="https://user-images.githubusercontent.com/9207770/37328426-1921eb4a-26c0-11e8-8e88-d64407ce586f.png">

**Comment by Niveathika92** [comment]
@dnwick This is fixed from SP4.3.0 onwards
