### ISSUE TITLE
Business rules view page needs a back button

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#1196]
**Description:**
Business rules view page needs a back button to the list view

**Suggested Labels:**
Business rules manager, Bug

**Suggested Assignees:**
@senthuran16 

**Steps to reproduce:**
Create a business rule, 
Click on the eye to view

**Comment by Niveathika92** [comment]
Closing as this is a duplicate of https://github.com/wso2/carbon-analytics/issues/1347
