### ISSUE TITLE
Lucene queries with upper-case letters and wild cards does not return correct results

### ISSUE THREAD

**Issue by tishan89** [wso2/carbon-analytics#1221]
**Description:**
This is happening because Lucene internally converts all queries to lowercase. There is an API option to override the behavior. Solution is to utilize that.

**Affected Product Version:**
DAS 3.1.0

**Steps to reproduce:**
Try a query in the format 'searchField:111-1111L*'

**Comment by Niveathika92** [comment]
Closing as the fix is merged
