### ISSUE TITLE
[Status Dashboard] Inline CSS should be remove

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#1235]
**Description:**
Inline CSS should be taken to separate CSS file.

**Suggested Labels:**
Improvement

**Comment by erangatl** [comment]
It's better to pass styles through a const, so the code looks nice. Not recommended to move MUI styles to CSS.

**Comment by NisalaNiroshana** [comment]
Closed the issue based on above comment. because it is not a valid requirement with the Material UI
