### ISSUE TITLE
[Status Dashboard] Ticks in line graphs displays in out of boundaries

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#1250]
**Description:**
Ticks in line graphs display in out of boundaries
![screenshot from 2018-05-21 18-21-09](https://user-images.githubusercontent.com/15528434/40313251-dccbca36-5d32-11e8-91cd-4b427d18e645.png)

**Suggested Labels:**
Bug

**Comment by CharukaK** [comment]
Couldn't re-produce in the latest pack.

**Comment by Yasara123** [comment]
@CharukaK You need to publish some events through JMeter(With http sample) and check. If graph is flat then this issue couln't see.

**Comment by shehan360** [comment]
![chart_bounds](https://user-images.githubusercontent.com/33398983/51029009-1fe9e280-15bb-11e9-9b05-bb9cec2894ae.png)

Issue can be reproduced in SP 4.4.0-m11 by running EI Analytics siddhi app and publishing to it through EI analytics client.

**Comment by Niveathika92** [comment]
This is fixed by https://github.com/wso2/carbon-analytics/pull/1636
