### ISSUE TITLE
[Business Rules] No cancel button for business rule delete modal

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#1348]
**Description:**
No cancel button for business rule delete modal

**Suggested Labels:**
Business Rules, Bug, Minor

**Suggested Assignees:**
@senthuran16 

**Affected Product Version:**
4.2 RC2

**OS, DB, other environment details and versions:**    
windows

**Steps to reproduce:**
Delete a business rule

**Comment by mohanvive** [comment]
@erangatl Can you please provide more context for this. Is this already fixed?

**Comment by erangatl** [comment]
When you delete a business rule, in the conformation modal there should be a Cancel button along with the Delete button.  This is not fixed yet.

![image](https://user-images.githubusercontent.com/20179540/53856023-295d5d00-3ff6-11e9-88d2-376b383fb95c.png)
