### ISSUE TITLE
Indexing fails throwing a BufferOverflowException when a large record is persisted

### ISSUE THREAD

**Issue by pcnfernando** [wso2/carbon-analytics#1354]
**Description:**
Even though the attributes is not marked to be indexed, during the enqueue process we append the whole record to the BigQueue. When the record entry exceeds the default BigQueue pagesize, indexing fails throwing a buffer-overflow exception.

**Affected Product Version:**
1.3.x

**Comment by dilini-muthumala** [comment]
Fixed with 30dfcd64f4faa62ca5fbf4699aff5ddf13a2cd59 hence closing the issue.
