### ISSUE TITLE
Editor Design View - In sink and source types should be pre populated

### ISSUE THREAD

**Issue by dnwick** [wso2/carbon-analytics#1359]
**Description:**
Currently user has to type the sink and source types. We need to pre populate them.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
SP 4.2.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Drag and drop a sink or a source and see the corresponding form

**Related Issues:**

**Comment by PradeepaJey1** [comment]
This had been implemented.

**Comment by Niveathika92** [comment]
Closing as it is fixed in SP 4.4.0-m10 version
