### ISSUE TITLE
[Business Rules] When there is an error in a template file cannot log in

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#1369]
**Description:**
When "templateGroup" is missing in a template file, cannot log in. No proper error handling.

**Suggested Labels:**
Business Rules, Bug, 

**Suggested Assignees:**
@minudika 

**Affected Product Version:**
4.2.0

**OS, DB, other environment details and versions:**    
Windows 10

**Related Issues:**

**Comment by Niveathika92** [comment]
This is also true if the templated siddhi app with default values does not pass the script validations.
