### ISSUE TITLE
[Business Rules] Should have an undeploy button

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#1371]
**Description:**
At the moment we need to delete the Business rule to undeploy, it's better to have an undeploy button to improve UX

**Suggested Labels:**
Improvement

**Suggested Assignees:**
@minudika 

**Affected Product Version:**
4.3.0-M1

**OS, DB, other environment details and versions:**    
Windows 10

**Comment by Niveathika92** [comment]
Closing as the feature is available with PR https://github.com/wso2/carbon-analytics/pull/1484
