### ISSUE TITLE
Cannot retrieve last hour's stats data from the REST API

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/carbon-analytics#1413]
**Description:**
When trying to retrieve stats data for the last hour using the REST API for aggregations, no data is returned. 
This behavior is the same for the **last 6 hours**. 

**Suggested Assignees:**
@Niveathika92

**Comment by Niveathika92** [comment]
As discussed offline, this was due to not sending the timezone when retrieving from aggregations.
