### ISSUE TITLE
[Status Dashboard] X-axis is not visible in graphs in Siddhi app view

### ISSUE THREAD

**Issue by Niveathika92** [wso2/carbon-analytics#1443]
**Description:**
$subject
![screenshot from 2018-09-17 07-32-52](https://user-images.githubusercontent.com/27669465/45732812-9ec9a280-bbfb-11e8-9912-fe541ddd7cb8.png)

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
@erangatl 

**Steps to reproduce:**
1. Add the worker node to the monitoring dashboard
2. Go to Siddhi App view page

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-analytics/pull/1630
