### ISSUE TITLE
[Editor] UI Freeze if a siddhi app containing store is started (if store is unreachable and retry)

### ISSUE THREAD

**Issue by niveathika** [wso2/carbon-analytics#1444]
**Description:**
$subject
![screenshot from 2018-09-17 07-41-32](https://user-images.githubusercontent.com/27669465/45733965-4a74f180-bc00-11e8-9c1a-32e2206c91cc.png)

**Suggested Labels:**
Type/Bug

**Comment by PradeepaJey1** [comment]
The above error was not produced for rdbms

**Comment by Niveathika92** [comment]
This is reproducible for MongoDB. Seems MongoDB tries to connect at the initialisation itself
