### ISSUE TITLE
Changing Siddhi app description from design view does not get relfected on the design canvas.

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/carbon-analytics#1445]
**Description:**
Changing Siddhi app description from design view does not get relfected on the design canvas.

**Affected Product Version:**
SP-4.3.0

**OS, DB, other environment details and versions:**    
Mac OS 10.13.1, Chrome Version 69.0.3497.92 (Official Build) (64-bit)

**Steps to reproduce:**
1. Create a siddhi app.
2. Switch to design view.
3. Click on 'App Annotation' button.
4. On the App Annotation form, edit the siddhi app description and click save.

I expected the new description to appear on the design canvas, but it still shows the old one.

**Comment by PradeepaJey1** [comment]
Fixed in https://github.com/wso2/carbon-analytics/pull/1576
