### ISSUE TITLE
[UX] Useless state in App Annotation editor form

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/carbon-analytics#1446]
**Description:**
<img width="1006" alt="screen shot 2018-09-21 at 7 57 13 pm" src="https://user-images.githubusercontent.com/7592890/45887242-dc375700-bdd8-11e8-9475-8ea3a0b445f2.png">

Above state of the form is not useful as all the input fields are disabled and user has nothing to do until he ticks the 'App Annotations' tick. 
Why do we have a tick infront of 'Siddhi App' ? 

**Affected Product Version:**
SP-4.3.0

**OS, DB, other environment details and versions:**    
Mac OS 10.13.1, Chrome Version 69.0.3497.92 (Official Build) (64-bit)

**Steps to reproduce:**
- Create a siddhi app.
- Switch to design view.
- Click on 'App Annotation' button.

**Comment by PradeepaJey1** [comment]
This has been fixed in 3fee55f68f2583327f704f7ba516d05e6672ccf8
