### ISSUE TITLE
[Editor-design-view] Saved attribute's type is not changed in the selectbox 

### ISSUE THREAD

**Issue by PradeepaJey1** [wso2/carbon-analytics#1499]
**Description:**
$subject. Saved attribute type never matches the option in the select-box because the text inside the option tag is not trimmed. This will return false for any saved data-type.

**Steps to reproduce:**
1. In the design-view, create a new stream
2. Assign an attribute with a data-type other than string
3. Click submit
4. Edit the saved stream 
5. Attribute's type is populated as "string"

**Comment by Niveathika92** [comment]
Closing this a s the fix is merged
