### ISSUE TITLE
Confusing tab header colors for Editor console

### ISSUE THREAD

**Issue by suhothayan** [wso2/carbon-analytics#1521]
**Description:**
It's confusing to identify which tab is open "console" or "From - ReciveAndCount" ? 

Also how to cancel the edit view is not prominent, "x" icon on the right is not in the right color, and it's confusing if we press that whether the full console section will be removed, or whether the form will get canceled? 

<img width="1186" alt="screen shot 2018-12-09 at 1 14 32 am" src="https://user-images.githubusercontent.com/3785208/49690029-231f2800-fb50-11e8-8f13-eca17125a3bd.png">

**Comment by erangatl** [comment]
Forms will have separate cancel buttons as well.
