### ISSUE TITLE
Implementation information displayed when item is dragged and dropped to editor

### ISSUE THREAD

**Issue by suhothayan** [wso2/carbon-analytics#1522]
**Description:**
Some internal reference information is printed in the panel when an item is dragged and dropped to the editor design view. 

<img width="195" alt="screen shot 2018-12-09 at 1 25 22 am" src="https://user-images.githubusercontent.com/3785208/49690126-b4db6500-fb51-11e8-8449-ca50cec4d43e.png">

**Comment by PradeepaJey1** [comment]
This is being fixed

**Comment by Niveathika92** [comment]
Closing as this is fixed with the above PR
