### ISSUE TITLE
[Editor] Run & Debug buttons are not getting disabled when file is closed

### ISSUE THREAD

**Issue by mohanvive** [wso2/carbon-analytics#1677]
**Description:**
There should be at least one Siddhi file opened to run or debug the application (because buttons are disabled when there is no any files). But once you close the file, those buttons are not getting disabled.

![button-enabled](https://user-images.githubusercontent.com/7523274/57211467-fc312900-6ffd-11e9-8e0a-36f3f56b2862.png)

**Suggested Assignees:**
@damith

**Affected Product Version:**
SP 4.4.0

**Comment by dnwick** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/1675
