### ISSUE TITLE
[Editor] Redundant 'OK' button for settings configuration

### ISSUE THREAD

**Issue by mohanvive** [wso2/carbon-analytics#1678]
**Description:**
When you click the settings configuration in Editor you will be getting a configuration box. In that, you can change the font size and etc instantly, it will be get applied and you don't have to click the 'OK' button. In this case, 'OK' button is redundant. 

**Suggested Assignees:**
@damithn

**Affected Product Version:**
SP 4.4.0

**Comment by dnwick** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/1675
