### ISSUE TITLE
[Editor] HTTP source gives an error for setting map type to anything other than json 

### ISSUE THREAD

**Issue by vithusiva** [wso2/carbon-analytics#1856]
**Description:**
http source gives an error for setting map type to anything other than json

**Comment by lasanthaS** [comment]
Hi @vithusiva, 

We tried to reproduce this issue using the following Siddhi app, but couldn't reproduce it. Therefore we are closing this issue. If you are experiencing the issue still, please re-open with the tested Siddhi app.
