### ISSUE TITLE
Change imported siddhi version from 0.0.0 to 4.0.0

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/carbon-analytics#305]
The siddhi version imported should change from `0.0.0` to `4.0.0` in all components.
```
<import.package>
            ...
            org.wso2.siddhi.*;version="0.0.0",
            *;resolution:=optional
</import.package>
```

**Comment by mohanvive** [comment]
Fixed with https://github.com/wso2/carbon-analytics/commit/e81de8642e5f270e85eeff689b26295fda9255fa .
