### ISSUE TITLE
Typos in the welcome page of the editor

### ISSUE THREAD

**Issue by nirmal070125** [wso2/carbon-analytics#329]
<img width="148" alt="screen shot 2017-06-29 at 7 59 18 pm" src="https://user-images.githubusercontent.com/413016/27693850-1485e1ae-5d08-11e7-927e-4f953bf1cb96.png">

/s/Key Concept/Key Concepts
/s/Siddhi Grammer/Siddhi Grammar

**Comment by erangatl** [comment]
Fixed with welcome page redesign
