### ISSUE TITLE
Feed Simulation- when you delete first simulation source accordion, all the others also get deleted

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#388]
![image](https://user-images.githubusercontent.com/20179540/29566410-689d6396-8767-11e7-895b-14e57af0f299.png)

![image](https://user-images.githubusercontent.com/20179540/29566424-7b3929cc-8767-11e7-9f3d-8b72d937c379.png)

**Comment by ramindu90** [comment]
fixed in 629cbce0e7e79af42e66c67ebd0760537ce9fbd0
