### ISSUE TITLE
When editor starts could see some error logs in the console.We should remove them.

### ISSUE THREAD

**Issue by dnwick** [wso2/carbon-analytics#402]
simulation/feed Failed to load resource: the server responded with a status of 404 (Not Found)
editor/commons/lib/log4javascript-1.4.13/log4javascript.js:148 {"status":"NOT_FOUND","message":"No simulation configurations available."}

**Comment by ramindu90** [comment]
fixed in b7f741247b761aaec64fb2396f00f7326136c3a3
