### ISSUE TITLE
Feed Simulation panel shows  "Active Feed Simulations, Inactive Feed Simulations" text when empty

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#404]
![screenshot-localhost 9090-2017-09-07-14-09-46](https://user-images.githubusercontent.com/20179540/30154115-8b1d2412-93d6-11e7-9ee0-1515b342a6fe.png)

Feed Simulation panel shows  "Active Feed Simulations, Inactive Feed Simulations" text when empty.
No need to categorize the simulations at all, we can disable the run button of inactive simulations

**Comment by ramindu90** [comment]
fixed in b7f741247b761aaec64fb2396f00f7326136c3a3
