### ISSUE TITLE
Editor single simulation, one should not be able to delete all the tabs.

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#405]
![screenshot-localhost 9090-2017-09-07-14-41-56](https://user-images.githubusercontent.com/20179540/30155641-f76acfb2-93da-11e7-8bfe-b8c5bdcdcf54.png)

Now after deleting a single simulation tab only, it adds a close button to the first single simulation.
When adding a second tab, the first tab should get a close button.  One should not be able to delete a tab if it is the only tab left.

**Comment by ramindu90** [comment]
fixed with pr: https://github.com/wso2/carbon-analytics/pull/800
