### ISSUE TITLE
Databridge config params are present in the product-sp's deployment.yaml

### ISSUE THREAD

**Issue by gokul** [wso2/carbon-analytics#429]
Ideally, these should be kept internally and added to the product deployment.yaml only when an override is required.

**Comment by Niveathika92** [comment]
@gokul Wouldn't it be more confusing, as we have seen people getting confused about where to change a functionality if no configs are present for instance SP auth configs

**Comment by Niveathika92** [comment]
Closing this as issue is moved to https://github.com/wso2/product-sp/issues/901
