### ISSUE TITLE
Product-sp editor doesn't show exceptions generated from Siddhi

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/carbon-analytics#444]
**Description:**

Product-sp editor doesn't show exceptions generated from Siddhi. Even the terminal doesn't show any exception.

**Suggested Labels:**

editor

**Suggested Assignees:**

@grainier 

**Affected Product Version:**
WSO2 Stream Processor 4.0.0 Milestone 12 Release!
**OS, DB, other environment details and versions:**    
Ubuntu 16.04
**Steps to reproduce:**
Debug the siddhi file with following:

define stream foo(id int,temp int);
define table fooTable(id int,temp int);
from foo
insert into fooTable; 

**Related Issues:**

**Comment by suhothayan** [comment]
@RAVEENSR 
Can't see any exceptions on the latest pack please verify.
