### ISSUE TITLE
Class cast exception is thrown when trying to Insert Into a table.

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/carbon-analytics#445]
**Description:**

In siddhi debugger all the insert into callbacks are cast into InsertIntoStreamCallbacks.

**Suggested Labels:**

editor

**Suggested Assignees:**

@grainier  

**Affected Product Version:**
WSO2 Stream Processor 4.0.0 Milestone 12 Release!
**OS, DB, other environment details and versions:**    
Ubuntu 16.04
**Steps to reproduce:**
Debug the siddhi file with following:

define stream foo(id int,temp int);
define table fooTable(id int,temp int);
from foo
insert into fooTable; 

**Related Issues:**

**Comment by grainier** [comment]
Ref: https://github.com/wso2/siddhi/commit/7cfcf26efa8487750d82af583d3c5a7f31f9d74a

**Comment by grainier** [comment]
Moved to https://github.com/wso2/siddhi/issues/570
