### ISSUE TITLE
Siddhi app text is not properly highlighted with colors when editor is run on Chromium browser

### ISSUE THREAD

**Issue by ChariniNana** [wso2/carbon-analytics#543]
**Description:**
Siddhi app text is not properly highlighted with colors when editor is run on Chromium browser

Relevant chromium version: 51.0.2704.79

**Suggested Labels:**
editor

**OS, DB, other environment details and versions:**    
OS version on which issue was encountered: Ubuntu 15.10 (64-bit)

**Steps to reproduce:**
1) Install relevant chromium version
2) Start the product SP with sh editor.sh command
3) Open the editor on chromium browser
4) Open a sample siddhi app. The colors would not be shown. When opened with Chrome the text is highlighted as expected

**Comment by RAVEENSR** [comment]
Tested on the chromium Version 62.0.3202.94 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit) and the editor works fine.

![chromium](https://user-images.githubusercontent.com/19996612/33708214-d660d948-db5f-11e7-91a6-a46e3dcfa21a.png)

![chromium2](https://user-images.githubusercontent.com/19996612/33708220-db48ad8c-db5f-11e7-8eb2-0ffcb6407e21.png)
