### ISSUE TITLE
Include capability to add gadgets level permissions in analytics and das

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/carbon-analytics#551]
**Description:**
Currently it's only supported to have dashboard level permissions, but it'll be better to include gadgets level permissions as well in analytics and das.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NisalaNiroshana** [comment]
Since this is a new feature request and we did not do any development for DAS, we will close the ticket. If there is any customer request, we will consider this issue again
