### ISSUE TITLE
Include capability to add data level permission in analytics.

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/carbon-analytics#552]
**Description:**
Currently when accessing the data through data explorer in management console, we only consider UI and service level permissions. And also through rest endpoints, we can provide permissions operation wise, but not in data level. Better to include data level permission as well (i.e. event table wise). 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruwanta** [comment]
In analytics space, all the tables should have the same level of permissions for a particular user. 

- Analytics

 data is not live-data.

- If

 any data is sensitive, then should not be stored at all.

- Analytics

 should concentrated about accuracy and speed of results, not the security.

Hence this feature should not be implemented. The necessary security needs to be handled via UI and REST API associated, but not at the data level.
