### ISSUE TITLE
MySQL JDBC driver being bundled in Stream Processor due to certain dependencies in carbon-analytics

### ISSUE THREAD

**Issue by ChariniNana** [wso2/carbon-analytics#568]
**Description:**
The com.mysql.jdbc jar (MySQL JDBC driver) gets bundled in WSO2 Stream Processor due to certain dependencies in carbon-analytics

**Suggested Assignees:**
Grainier

**Comment by mohanvive** [comment]
It is fixed now. com.mysql.jdbc jar is not getting packed now.
