### ISSUE TITLE
Can't edit feed simulator

### ISSUE THREAD

**Issue by ChariniNana** [wso2/carbon-analytics#578]
**Description:**
An existing feed simulator cant be edited. 

**Suggested Labels:**
editor

**Steps to reproduce:**
Create a feed simulator -> save -> click edit -> change stream for simulation -> try to save
the simulator doesnt get saved

**Comment by ramindu90** [comment]
added fixes in pr: https://github.com/wso2/carbon-analytics/pull/739
@ChariniNana : please confirm whether the issue is fixed.

**Comment by ChariniNana** [comment]
@ramindu90 this issue is fixed
