### ISSUE TITLE
Capability to merge multiple event tables when populating a custom gadget

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/carbon-analytics#608]
**Description:**
When creating a custom gadget from analytics dashboard, it's better to have an option to merge data from multiple event tables when populating the gadget. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by mohanvive** [comment]
I don't think above should be part of gadget functionality. @NisalaNiroshana , can you please review this and comment.
