### ISSUE TITLE
Feed Simulator gives unnecessary WARN log

### ISSUE THREAD

**Issue by Anoukh** [wso2/carbon-analytics#625]
**Description:**
When a Feed Simulator is saved the following WARN log is displayed in the console 
`[2017-11-06 17:51:38,973]  WARN {org.wso2.carbon.event.simulator.core.internal.generator.random.core.RandomEventGenerator} - Time interval is required for random data simulation of stream 'SweetProductionStream'. Time interval will be set to 1 second for source configuration : {"simulationType":"RANDOM_DATA_SIMULATION","attributeConfiguration":[{"type":"CUSTOM_DATA_BASED","list":["candy","peanut-butter-cup","truffle","caramel-bar"]},{"min":"0","max":"30","precision":"0","type":"PRIMITIVE_BASED","primitiveType":"FLOAT"}],"streamName":"SweetProductionStream","siddhiAppName":"Sweet-Factory-Analytics-6"}
[2017-11-06 17:51:38,974]  INFO {org.wso2.carbon.event.simulator.core.service.SimulationConfigDeployer} - Deployed active simulation 'SweetProductionStream-5'.
`
It says the time interval is not given and a default value will be used even though a time interval is given. But the value is actually taken. For example if value of 10000ms is given, it will work correctly but log will be displayed. 

**Suggested Labels:**
Type/Bug
Priority/Low

**Suggested Assignees:**
@dnwick 

**Steps to reproduce:**
Create and save a Feed Simulator with a value given for interval and check console

**Comment by ramindu90** [comment]
fixed with pr: https://github.com/wso2/carbon-analytics/pull/791
