### ISSUE TITLE
Bottom Bar of Editor covers console

### ISSUE THREAD

**Issue by Anoukh** [wso2/carbon-analytics#626]
**Description:**
The bottom bar covers a part of the console

![image](https://user-images.githubusercontent.com/8677511/32441239-b712b5da-c31c-11e7-9fab-e626a392c502.png)

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
@dnwick 

**OS, DB, other environment details and versions:**    
Ubuntu 16. Chrome running on a 1920x1080 Resolution display

**Comment by erangatl** [comment]
Fixed with #640
