### ISSUE TITLE
Editor shows console log on startup

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#644]
**Description:**
Now when the Editor is started console is also opened and show some logs. On startup we should not display the console log, it's not a good experience. And the console log should contain logs for actions performed within Editor. 

![screenshot-10 100 5 166 9390-2017-11-13-11-36-08](https://user-images.githubusercontent.com/20179540/32711853-29a94524-c867-11e7-96b1-becaf6857f54.png)

**Suggested Labels:**
Editor, Improvement, UX

**Comment by ramindu90** [comment]
fixed in pr: https://github.com/wso2/carbon-analytics/pull/772
