### ISSUE TITLE
Ace editor has a inbuilt support for find and replace , but we need to add a editor functionality binding to it 

### ISSUE THREAD

**Issue by dnwick** [wso2/carbon-analytics#666]
**Description:**
When press Ctrl + f or click from file menu need to bring up the find and replace box

**Comment by ramindu90** [comment]
Need to add styling and add to "edit menu" as well

**Comment by ramindu90** [comment]
styling done in commit by eranga: e3974c8f97646db1e775eb920b5754fd18f1f14a

**Comment by ramindu90** [comment]
faunctionality added in pr: https://github.com/wso2/carbon-analytics/pull/791
