### ISSUE TITLE
Editor Doc provide default url in ' Using+the+Stream+Processor+Studio' section

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#675]
**Description:**
It's good to provide the default URL , in the following location
https://docs.wso2.com/display/SP400/Using+the+Stream+Processor+Studio

![url](https://user-images.githubusercontent.com/20179540/33070323-afc60314-cedd-11e7-808d-bd7761de695a.png)

**Suggested Labels:**
Editor, Doc, Improbement

**Suggested Assignees:**
Rukshani

**Comment by ramindu90** [comment]
this is fixed
