### ISSUE TITLE
Editor Feed simulator when editing an existing simulation uploaded CSV files does not show. 

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#678]
**Description:**
When editing an existing simulation, uploaded CSV files does not show. 

**Suggested Labels:**
Editor, Bug

**Steps to reproduce:**
Create a new feed simulation
Upload a CSV file
Save simulation.
Edit the simulation.
CSV files does not show

**Comment by ramindu90** [comment]
fixed in pr: https://github.com/wso2/carbon-analytics/pull/735
