### ISSUE TITLE
Editor single simulation panel hide the run/debug switch and just show a notification

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#689]
**Description:**
Single simulation panel hide the run?debug switch and just show a notification

![image](https://user-images.githubusercontent.com/20179540/33166669-17f0ff96-d061-11e7-95ee-a45acf01c93a.png)

**Suggested Labels:**
Component/Studio, Improvement

**Comment by ramindu90** [comment]
added a work around with commit: 0ec95c502da222fe688861b08d6921b27bb1485b
@erangatl : please close this if the fix resolves the issue.

**Comment by ramindu90** [comment]
fixed in pr: https://github.com/wso2/carbon-analytics/pull/820
