### ISSUE TITLE
Syntax error marker gives false errors sometimes. (sec,min,hour)

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#694]
**Description:**
Syntax error marker gives false errors sometimes. (sec,min,hour)

![screenshot-192 168 56 1 9390-2017-11-23-16-52-43](https://user-images.githubusercontent.com/20179540/33170645-09f241a8-d06f-11e7-9d51-a11abca27d3c.png)

**Suggested Labels:**
Component/Studio, Bug

**Comment by RAVEENSR** [comment]
fixed in commit d9525e9
