### ISSUE TITLE
Editor when the app is started through simulation panel it cannot be stopped 

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#695]
**Description:**
When the app is started through simulation panel it cannot be stooped

**Suggested Labels:**
Component/Studio , Bug

**Steps to reproduce:*
Start a siddhi app in run or debug mode through simulation panel.
Got to Run -> Stop

**Comment by ramindu90** [comment]
fixed with pr: https://github.com/wso2/carbon-analytics/pull/732
