### ISSUE TITLE
org.wso2.carbon.stream.processor.statistics.feature packs unnecessary bundles

### ISSUE THREAD

**Issue by this** [wso2/carbon-analytics#699]
**Description:**
`org.wso2.carbon.stream.processor.statistics.feature` feature packs `msf4j-core` bundle. See [feature pom.xml](https://github.com/wso2/carbon-analytics/blob/v2.0.158/features/org.wso2.carbon.stream.processor.statistics.feature/pom.xml#L120-L123).

**Suggested Assignees:**
@Yasara123 

**Affected Product Version:**
v2.0.158

**Comment by ramindu90** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/716
