### ISSUE TITLE
Status Dashboard : Legend Panel only shows the 1st 5 legends

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#729]
**Description:**
At worker history page legend panel only shows the 1st 5 legends

**Suggested Labels:**
Bug

**Suggested Assignees:**
@CharukaK 

**Affected Product Version:**
4.0.0-Beta

**Comment by CharukaK** [comment]
I checked the issue legend seems to be working fine with more than 5 items
![screenshot from 2017-12-06 14-18-46](https://user-images.githubusercontent.com/18122888/33652769-9848baf6-da90-11e7-8fe5-b91ed001cd74.png)
