### ISSUE TITLE
If siddhi app name lengthy "ReceiveHTTPInJsonFormatWithCustomMapping", workspace directory tab is not working properly.

### ISSUE THREAD

**Issue by ksdperera** [wso2/carbon-analytics#750]
**Description:**
If siddhi app name lengthy"ReceiveHTTPInJsonFormatWithCustomMapping", workspace directory tab is not working properly at the first time. After expanding the workspace tab it works fine. 

![screenshot from 2017-11-29 19-34-03](https://user-images.githubusercontent.com/5366557/33378916-6e6b955e-d53c-11e7-84ad-90a049472865.png)

**Comment by dnwick** [comment]
this is fixed but need to provide hover functionality to show full text

**Comment by RAVEENSR** [comment]
Fixed by @dnwick in PR https://github.com/wso2/carbon-analytics/pull/937
