### ISSUE TITLE
Editor when there are no feed simulations are available simulation tab cannot be toggled

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#773]
**Description:**
Editor, when there are no feed simulations, are available simulation tab is disabled.

![image](https://user-images.githubusercontent.com/20179540/33618250-03d5ca22-da08-11e7-9c7d-8687107a53ae.png)

**Suggested Labels:**
Editor, Bug

**Suggested Assignees:**
@ramindu90

**Comment by ramindu90** [comment]
fixed in pr: https://github.com/wso2/carbon-analytics/pull/791
