### ISSUE TITLE
Editor after deleting a siddhi file single simulation data related to that file needs to be cleared.

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#774]
**Description:**
After deleting a siddhi file simulation data related to that file needs to be cleared.

**Suggested Labels:**
Editor, Bug

**Suggested Assignees:**
@ramindu90 

**Steps to reproduce:**
Add a  single simulation
Delete the related siddhi file.
Open single simulation panel.

**Comment by ramindu90** [comment]
fixed in commit: 81c7367342ff0e3c623f51ad87b34f653b11158a
