### ISSUE TITLE
Tooltip doesn't fade away when going away from the selected place 

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/carbon-analytics#777]
**Description:**
In product-sp editor the tooltip doesn't fade away when the user takes away mouse pointer from the selected places. This happens when the tooltip is produced in the last line of a file.(without a new line at the end)

**Affected Product Version:**
Product-SP beta2

**OS, DB, other environment details and versions:**    
Ubuntu 16.04, Chrome browser
![tooltip](https://user-images.githubusercontent.com/19996612/33646004-bb8736cc-da73-11e7-8c68-913d2105efb7.png)

**Comment by RAVEENSR** [comment]
This issue occurred due to a failure of a back end call. This is fixed now.

**Comment by RAVEENSR** [comment]
This issue is still there in the pack. 

Type the following lines in the siddhi file and place the cursor on the 's'.

@App:name("SiddhiApp")
@app:description("Description of the plan")

-- Please refer to https://docs.wso2.com/display/SP400/Quick+Start+Guide on getting started with SP editor. 

define stream s

**Comment by Niveathika92** [comment]
This cannot be reproduced in SP 4.3.0
