### ISSUE TITLE
Status Dashboard :  Remember me Function is not working

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#779]
**Description:**
In status dashboard token remembering function is not working.

**Suggested Labels:**
Bug

**Suggested Assignees:**
@Yasara

**Affected Product Version:**
Beta2

**Comment by mohanvive** [comment]
@Yasara123 , AFAIR above issue is fixed now. Can you please share the PR, commit id and close the issue.

**Comment by Yasara123** [comment]
Fixed in #942
