### ISSUE TITLE
Status Dashboard : In Tooltips displays in milliseconds instead of date.

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#781]
**Description:**
In tooltips displays in milliseconds instead of date while axis contains the date

**Suggested Labels:**
Bug

**Suggested Assignees:**
@CharukaK

**Affected Product Version:**
Beta2

**Comment by CharukaK** [comment]
Fixed in wso2/react-vizgrammar#30

**Comment by suhothayan** [comment]
@Yasara123 can you check this

**Comment by mohanvive** [comment]
@Yasara123 , Please update on this issue. Whether above reported issue is solved now?

**Comment by Yasara123** [comment]
Yes it is Fixed
