### ISSUE TITLE
Status Dashboard : Legends are cuttof

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#796]
**Description:**
Legends are cutoff from the margin. cannot change font size and cannot add more than 5 graphs. 
![screenshot from 2017-12-07 02-32-50](https://user-images.githubusercontent.com/15528434/33713779-94c3dedc-db72-11e7-9d92-f97b5107bc39.png)

**Suggested Labels:**
Bug

**Suggested Assignees:**
@CharukaK

**Comment by CharukaK** [comment]
This is the same issue in #729 as I have mentioned in [here](https://github.com/wso2/carbon-analytics/issues/729#issuecomment-349573982) it's working in my test I did and are you using the latest version of react-vizgrammar here in this screenshots shown?

**Comment by lasanthaS** [comment]
Closing the issue since it has been fixed.
