### ISSUE TITLE
Siddhi app doesn't start properly when it's started from event simulator in editor

### ISSUE THREAD

**Issue by ChariniNana** [wso2/carbon-analytics#802]
**Description:**
Siddhi app doesn't start properly when it's started from single event simulator. When the simulator is run for the first time, the siddhi application runs without an issue and correct results are produced. When the application is stopped, and then we try to send events from single event simulator again, the app doesn't start properly. (However, partial results were seen in the case of running an incremental aggregation application on editor)

**Suggested Labels:**
Bug/ Editor

**Suggested Assignees:**
@ramindu90 

**Steps to reproduce:**
1. Run the editor
2. Create a siddhi app
3. Simulate it with single event simulator. Application would start and work properly
4. Stop the application
5. Send events again from single event simulator. Application does not show that it has been started

**Comment by ramindu90** [comment]
fixed in pr: https://github.com/wso2/carbon-analytics/pull/820
