### ISSUE TITLE
Simulator UI fixes

### ISSUE THREAD

**Issue by ramindu90** [wso2/carbon-analytics#829]
**Description:**
> Disable all menu items and single simulation tab when "create feed simulations" is opened
> Fix CSS in tooltips in inactive feed simulations
> Icon for tooltips in inactive feed simulations

**Comment by mohanvive** [comment]
@ramindu90 , Please update on this issue. Close, if above tasks are completed now..

**Comment by ramindu90** [comment]
@mohanvive 
Disable all menu items and single simulation tab when "create feed simulations" is opened is fixed

the following should be addressed. Since when the simulation is in the inactive state, the user doesn't know hovering on the simulation tab gives the reason for inactiveness.
  Fix CSS in tooltips in inactive feed simulations
  Icon for tooltips in inactive feed simulations
@erangatl can we look into this?
