### ISSUE TITLE
Status Dashboard : Charts Some configuration are hardcoded.

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#854]
**Description:**
Cannot change some properties like pie chart: fontsize , inline chart: line thikness, padding  and Inline chart does not scale to 100%
![screenshot from 2017-12-12 12-44-54](https://user-images.githubusercontent.com/15528434/33872040-329f3964-df3b-11e7-84de-a5ffde62b76e.png)

**Suggested Labels:**
Bug

**Suggested Assignees:**
@charukak

**Comment by CharukaK** [comment]
fixed in wso2/react-vizgrammar#48
