### ISSUE TITLE
Status Dashboard : Support only mysql and H2

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#855]
**Description:**
Support only mysql and H2

**Suggested Labels:**
Bug

**Suggested Assignees:**
@Yasara123

**Affected Product Version:**
Beta3

**Comment by Yasara123** [comment]
Added MSSQL

**Comment by Yasara123** [comment]
Support Oracle Fixed in 32aebd1

**Comment by this** [comment]
Fixed via https://github.com/wso2/carbon-analytics/pull/1045
