### ISSUE TITLE
When trying to build editor core separately build gets failed.

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/carbon-analytics#861]
**Description:**
When trying to build editor core separately build gets failed.

[INFO] org.wso2.carbon.siddhi.editor.core.internal.EditorMicroservice.handleGet(Request) may fail to clean up java.io.InputStream [org.wso2.carbon.siddhi.editor.core.internal.EditorMicroservice] Obligation to clean up resource created at EditorMicroservice.java:[line 160] is not discharged OBL_UNSATISFIED_OBLIGATION
[INFO] 

To see bug detail using the Findbugs GUI, use the following command "mvn findbugs:gui"

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.573 s
[INFO] Finished at: 2017-12-12T14:25:44+05:30
[INFO] Final Memory: 51M/444M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:check (analyze-compile) on project org.wso2.carbon.siddhi.editor.core: failed with 1 bugs and 0 errors -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Affected Product Version:**
carbon-analytics 2.0.201

**Steps to reproduce:**
Build editor core using "mvn clean install"

**Comment by mohanvive** [comment]
This is expected due to findbugs configs, You should build from parent folder and use a similar option like below.

> mvn clean install -rf :carbon-analytics-common-osgi-tests
