### ISSUE TITLE
Status Dashboard: Move private gadgets to react-vizgramma.

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#865]
**Description:**
Move private gadgets to react-vizgramma and necessary formatting & Styling chages. 

**Suggested Labels:**
Improvement

**Suggested Assignees:**
@Yasara123

**Comment by mohanvive** [comment]
Fixed with https://github.com/wso2/carbon-analytics/commit/bbb066d61f625e5e28b09b91ec2e5a2dc09ed919.
