### ISSUE TITLE
Editor doesn't get synced between tabs

### ISSUE THREAD

**Issue by Irindu** [wso2/carbon-analytics#866]
**Description:**
Opening the editor in a new tab of the same browser or a different browser while running a simulation on the first, breaks the simulation on the first browser tab and the event updates are only seen on the second browser tab but the app can only be closed from the first tab

**Suggested Labels:**
 Editor, bug/improvement

**Affected Product Version:**
 SP-4.0.0-bets3

**OS, DB, other environment details and versions:**    
Ubuntu/Linux, Firefox 57, Chrome 63

**Steps to reproduce:**
1)open a terminal and cd into <SP_HOME>/bin directory and issue./editor.sh to start the editor
2)Click new to create a new siddhi app
3)Save the app click File->save or Ctrl+S
4)Run the siddhi app click Run->Run or press Ctrl+R
5)Click on the Event Simulator Icon press Ctrl+shift+I
6)Also open the output console click the icon or Ctrl+shift+C
7)Send some events and observe the output
8)Open the editor in a new tab of the same browser or a different browser and try sending the events 
The console output is only shown in the second tab but the app can only be stopped from the first tab.

**Suggestions:**
Either the updates must be seen from both the tabs or the updates of the first tab should be delivered to the first tab

**Comment by dnwick** [comment]
Now if you start another tab while on going simulation in another, A message will be directed to older console saying connection has been closed. If you send events on new one , events will come to new tab. If you want to send events and see output in older console you need to refresh. Message will include sufficient information for user.
