### ISSUE TITLE
When wrong username or password entered, It will direct to a blank page in Status Dashboard.

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/carbon-analytics#869]
**Description:**
When we enter a wrong username or password on the login page of the Status Dashboard, then it will direct to a blank page without showing an error message. Then we need to refresh again,  

**Suggested Labels:**
Type/bug, Severity/minor

**Suggested Assignees:**
@Yasara123 

**Affected Product Version:**
dashborad version: v4.0.0.beta4
productSP: wso2sp-4.0.0-beta3
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu.
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110

**Steps to reproduce:**
Enter the invalid username or password on the login page. It will direct to a blank page. 

**Suggestion**
It better to show an error message saying "invalid username or password" on the same page.

**Comment by mohanvive** [comment]
The issue is fixed as per above commits.
