### ISSUE TITLE
Failure Siddhi App sample AlertsAndThresholds 

### ISSUE THREAD

**Issue by Irindu** [wso2/carbon-analytics#879]
**Description:**
Siddhi App sample AlertsAndThresholds fails with the following error

![image](https://user-images.githubusercontent.com/19923256/33923860-70b2880a-dff9-11e7-8104-91487efebd98.png)

**Suggested Labels:**
bug,editor,samples

**Affected Product Version:**
 SP-4.0.0-bets3

**OS, DB, other environment details and versions:**    
Ubuntu/Linux, Firefox 57,Chrome 63

**Steps to reproduce:**
1)open a terminal and cd into <SP_HOME>/bin directory and issue./editor.sh to start the editor
2)Click AlertsAndThresholds in the Try out samples section
3)Follow the instructions in the comments section to save the app configure the requiremnts in Prerequisites section carefully and run it 

it fails! with the following error ![image](https://user-images.githubusercontent.com/19923256/33924423-0bc6363c-dffc-11e7-8b00-a1c59eb65be2.png)

**Comment by mohanvive** [comment]
@ChathurikaA @gimantha We have found a solution for this. Whether it is documented?

**Comment by ChathurikaA** [comment]
This was fixed in siddhi-io-email 1.0.8 version and product-sp v4.0.0-beta5.

**Comment by Irindu** [comment]
issue fixed, tested on sp v4.00beta6SNAPSHOT

**Comment by Irindu** [comment]
Issue seen again in SP v4.0.0-RC1

**Comment by Irindu** [comment]
False Alarm app is working fine
