### ISSUE TITLE
Editor import and export need to improve by loading the file system in browser host machine.

### ISSUE THREAD

**Issue by ksdperera** [wso2/carbon-analytics#880]
**Description:**
As per the current implementation, the import and export functionality has loaded the file system in a server running machine,  because of that user may need to upload the siddhi files into a server running machine and then using editor open that files. Also, we should not let users access folders on the server machine except deployment/workspace.

**Comment by ChathurikaA** [comment]
Currently editor support only localhost. Therefore editor can import and export only files in the local machine.
