### ISSUE TITLE
Editor: After a stream is deleted in the siddhi app and saved, still the event simulator allows to send events to deleted stream

### ISSUE THREAD

**Issue by Niveathika92** [wso2/carbon-analytics#882]
**Description:**
Editor: After a stream is deleted in the siddhi app and saved, still the event simulator allows to send events to deleted stream.

**Suggested Labels:**
Editor, Bug

**Suggested Assignees:**
@ramindu90 

**Affected Product Version:**
SP-4.0.0-beta3

**Steps to reproduce:**
1. Define 2 streams and a query in a siddhi app
2. Save the siddhi app
3. Open the simulator pane.
4. Delete a stream
5. Save the siddhi-app
6. Select the deleted stream in the simulator pane
7. Send an event

**Comment by ramindu90** [comment]
fixed with commit : https://github.com/wso2/carbon-analytics/commit/ad55ec714167d3489b991e754aafda085c5770cc
