### ISSUE TITLE
 Status Dashboard: Create table query is not a support of other DB than H2 and MySql

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics#883]
**Description:**
Create table query is not a support of other DB than H2 and MySql and it is not a prepared statement. Need to support Oracle and MSSQL.

**Suggested Labels:**
Bug

**Suggested Assignees:**
@Yasara123

**Comment by Yasara123** [comment]
Fixed in e325a87

**Comment by mohanvive** [comment]
@Yasara123 , Hope you have fixed for other database types as well. Please update the issue and close it if necessary.

**Comment by Yasara123** [comment]
Fixed in 4c75e4b1f29a835b8e72570103b4fe819a8513df for Oracle
