### ISSUE TITLE
Editor: When a siddhi app is changed when the simulation is running, the app is not stopped

### ISSUE THREAD

**Issue by Niveathika92** [wso2/carbon-analytics#884]
**Description:**
When a siddhi app is changed when the simulation is running, the app is not stopped, events can still be sent through the simulator. Moreover, even when the stop button is disabled, the the button can be pressed.

**Suggested Labels:**
Editor, Bug

**Suggested Assignees:**
@ramindu90 

**Affected Product Version:**
SP-4.0.0-Beta3

**Comment by ramindu90** [comment]
@Niveathika92 : "When a siddhi app is changed when the simulation is running, the app is not stopped, events can still be sent through the simulator" issue has been fixed. Please confirm
I will look into "even when the stop button is disabled, the the button can be pressed"

**Comment by ramindu90** [comment]
fixed with PR: https://github.com/wso2/carbon-analytics/pull/1093
