### ISSUE TITLE
Status DashBoard: Unauthorized Error message is shown for non security issues.  

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/carbon-analytics#885]
**Description:**
In Status DashBoard, unauthorized error message is shown due to connection failure. 
![yasra11](https://user-images.githubusercontent.com/24618493/33937096-1d42298a-e028-11e7-8019-b443cc9f36fa.png)

**Suggested Labels:**
Type: bug, Severity: minor

**Suggested Assignees:**
@Yasara123 
**Affected Product Version:**
carbon-analytics version: v2.0.0
productSP: wso2sp-4.0.0-beta3

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu.
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110

**Comment by mohanvive** [comment]
Fixed with https://github.com/wso2/carbon-analytics/commit/08f9873dd8552653bc26f71299bb4f723622d31f .
