### ISSUE TITLE
In Business rules, the username should be displayed

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-analytics#905]
**Description:**
In Business rules, the username should be displayed.
For eg:
![screenshot from 2017-12-12 15-04-58](https://user-images.githubusercontent.com/30232477/33990938-b6fa3e6c-e0f2-11e7-8b4e-3ff95a0d3d91.png)

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Comment by mohanvive** [comment]
Closing the issue due to duplication.
