### ISSUE TITLE
Cannot put or remove debug point after a file is debugged.

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/carbon-analytics#907]
**Description:**
After a file is debugged (with or without debug points being added) we cannot add debug points again.

**Affected Product Version:**
product-sp-beta3

**OS, DB, other environment details and versions:**    
Firefox browser, Chrome browser version 62, Ubuntu 16.04

**Steps to reproduce:**
Create a siddhi app with following lines and save it.

@App:name("siddhiapp2")
@app:description("Description of the plan")

define stream stream1(id INT);

from stream1
select id
insert into stream2;

Start debug(with or without debug points).
Stop debug.
Try to add/remove debug points again.

![debuggererror](https://user-images.githubusercontent.com/19996612/33995101-e3e597cc-e102-11e7-9a94-4df24fd65f98.gif)

**Comment by dnwick** [comment]
This is fixed with https://github.com/wso2/carbon-analytics/pull/981
