### ISSUE TITLE
Need to add right click functionalities for delete etc on worksapce files

### ISSUE THREAD

**Issue by dnwick** [wso2/carbon-analytics#932]
**Description:**
Providing right click functionality for delete etc on files

**Comment by erangatl** [comment]
For Workspace -> Run All, Debug All, Stop All, Delete All
For individual files -> Run, Debug, Stop, Delete
https://docs.google.com/document/d/1-ik_mjunBCQcAvhT6s47q84urZFrz4dwx2WXJMYUdHg/edit
