### ISSUE TITLE
Editor tabs disappearing when pasting large content

### ISSUE THREAD

**Issue by ramindu90** [wso2/carbon-analytics#951]
**Description:**
$subject

**Steps to reproduce:**
> File -> New
> Delete all content
> Copy and paste a sample content with a description 
> All editor tabs gets hidden

<img width="1440" alt="screen shot 2017-12-17 at 8 43 57 pm" src="https://user-images.githubusercontent.com/10056966/34080887-1fc66c52-e36b-11e7-89a1-09da1e47ca0a.png">

**Comment by erangatl** [comment]
Fixed with #947
