### ISSUE TITLE
In Business Rules, It is better to have a button to go back to previous step.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-analytics#960]
**Description:**
In Business Rules, It is better to have a button to go back to previous step. Because if user mistakenly select the wrong one, no way to go back.

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta6

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Comment by senthuran16** [comment]
We can traverse forward / backward using the browser's buttons (or shortcut keys). Each step is considered as a page, so that if a user selects a wrong template group for example - he/she can go back and select a different one and proceed further.
