### ISSUE TITLE
 Conflicting shortcuts for Firefox 57 Crtl+Shift+I

### ISSUE THREAD

**Issue by Irindu** [wso2/carbon-analytics#966]
**Description:**
The stop shortcut in the run menu of the editor conflicts with the new private window shortcut of firefox

![image](https://user-images.githubusercontent.com/19923256/34093417-1bede140-e3ee-11e7-8220-0a46a2635793.png)

![image](https://user-images.githubusercontent.com/19923256/34093482-72977df8-e3ee-11e7-8017-57f0efff7540.png)

**Suggested Labels:**
Editor, improvement

**Affected Product Version:**
 sp-4.0.0-beta6-SNAPSHOT

**OS, DB, other environment details and versions:**    
Ubuntu/Linux, Firefox 57

**Steps to reproduce:**
1)open a terminal and cd into <SP_HOME>/bin directory and issue./editor.sh to start the editor
2)Click new to create a new siddhi appo
3)Create the following siddhi app

@App:name("cargo")
define stream CargoStream (weight int);
@sink(type='log', prefix='LOGGER')
define stream OutputStream(weight int, totalWeight long);
@info(name='CargoWeightQuery')
from CargoStream
select weight, sum(weight) as totalWeight
insert into OutputStream;

3)Save the app click File->save or Ctrl+S
4)Run the siddhi app click Run->Run or Ctrl+R

try to simulate the siddhi app with shortcut Ctrl+Shift+I

**Comment by RAVEENSR** [comment]
This happens when you don't focus on the editor area. Then  what will happen is your command will  be send to browser. So the browser default command will be triggered. So if you want to use this command you have to focus on the editor area.

**Comment by mohanvive** [comment]
Resolving the issue as per above comment.
