### ISSUE TITLE
In Business rules, As soon as session got expired, if we login again logout button is displayed in the business rules manager.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-analytics#971]
**Description:**
In Business rules, As soon as session got expired, if we login again, logout button is displayed in the business rules manager page and automatically redirected to the log in page.

**Suggested Labels:**
bug

**Suggested Assignees:**
@senthuran16 

**Affected Product Version:**
wso2sp-4.0.0-beta6

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu

**Steps to reproduce:**
1) After session out, you login to business rule as soon as possible.
2) Then the logout button is displayed in the business rules page and automatically redirected to the login page again.
![screenshot from 2017-12-18 14-51-06](https://user-images.githubusercontent.com/30232477/34099528-c33f5d04-e405-11e7-8497-7265593ddf77.png)

**Comment by gokul** [comment]
Closed by the above commit.
