### ISSUE TITLE
Feed simulation error in saving a empty form

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#982]
**Description:**
When trying to save an empty form it shows a technical error. Rather show a validation message to add a simulation source

![image](https://user-images.githubusercontent.com/20179540/34111231-22a9b5cc-e42f-11e7-9d11-bebefe047a56.png)

**Suggested Labels:**
Editor, Bug

**Comment by dnwick** [comment]
this is fixed in https://github.com/wso2/carbon-analytics/pull/1020
